version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "1337:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./flag:/var/www/flag
        links:
            - php-fpm

    php-fpm:
        build: .
        volumes:
            - ./src:/var/www/html