apiVersion: v1
kind: Pod
metadata:
  name: hidden-flag-pod
  namespace: kube-system
spec:
  initContainers:
    - name: init-flag
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - >
          FLAG=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 28);
          echo "The flag is: csc{$FLAG}" > /mnt/flag/flag.txt;
      volumeMounts:
        - name: flag-volume
          mountPath: "/mnt/flag"
  containers:
    - name: flag-container
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "sleep infinity"
      volumeMounts:
        - name: flag-volume
          mountPath: "/mnt/flag"
  volumes:
    - name: flag-volume
      emptyDir: {}
