import os
from PIL import Image, ImageDraw, ImageFont

FLAG = os.getenv("FLAG")

def hide_flag_image(flag_image, target_image, output_file=None):
    image = Image.open(target_image)
    for i in range(flag_image.size[0]):
        for j in range(flag_image.size[1]):
            original_pixel_value = image.getpixel(xy=(i+25,j+25))
            r = original_pixel_value[0]
            g = original_pixel_value[1]
            b = original_pixel_value[2]
            a = original_pixel_value[3]
            bw = flag_image.getpixel(xy=(i,j))
            new_g = g|1 if bw[1] > 127 else g&254
            g = new_g
            new_value = (r,g,b, a)
            image.putpixel(xy=(i + 25,j + 25), value=new_value)
    if output_file:
        image.save(output_file, "PNG")
    return image

def create_flag_rectangle_image(flag, output_file=None):
    image = Image.new(mode="RGBA", size=(len(flag)*20, 64), color="black")
    text_layer = Image.new('RGBA', image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(text_layer)
    draw.text((10,10), flag, fill="white", font=ImageFont.load_default(size=24))
    res_image = Image.alpha_composite(image.convert("RGBA"), text_layer)
    if output_file:
        res_image.save(output_file, "PNG")
    return res_image

def append_image(embedded_image_file, target_image_file, output_file):
    with open(target_image_file, "rb") as f:
        b1 = bytearray(f.read())
    
    with open(embedded_image_file, "rb") as f:
        b1.extend(f.read())
    
    with open(output_file, "wb") as f:
        f.write(b1)

flag_image = create_flag_rectangle_image(FLAG, 'hi.png') # first step, creating the flag image.

secret_image = hide_flag_image(flag_image, target_image="the_rock.png", output_file="secret.png") # Hiding that flag inside an image.

append_image(embedded_image_file="secret.png", target_image_file="kevin_hart.png", output_file="challenge.png") # hiding secret.png inside of flag.png and the output is challenge.png(final challenge)


"""
The flag image is generated by creat_flag_image(), but not saved. 
The flag is hidden inside first.png, resulting in flag.png.
That flag.png is then appended to another image called secret.png, resulting in challenge.png image.

Solution should be like this:
    - binwalk
    - stegsolve --> green bit plane 0

"""